package {{ .PackageName }}

type ApiGroup struct {
	// Code generated by github.com/BJYW/gin-vue-admin/server Begin; DO NOT EDIT.

	// Code generated by github.com/BJYW/gin-vue-admin/server End; DO NOT EDIT.
}
